### ISSUE TITLE
Error: Running Veris

### ISSUE THREAD

**Issue by rubenflx** [tbuzzelli/Veris#6]
I'm running Windows 10 and I downloaded the latest JAR for Veris.
I used the following commands to run Veris:

set path="C:\Program Files\Java\jdk-11.0.2\bin"
java -jar Veris.jar

I got this error:

Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
        at javafx.scene.image.Image.loadImage(Image.java:1060)
        at javafx.scene.image.Image.initialize(Image.java:799)
        at javafx.scene.image.Image.<init>(Image.java:702)
        at com.verisjudge.Main.<clinit>(Main.java:20)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
        at javafx.scene.image.Image.loadImage(Image.java:1060)
        at javafx.scene.image.Image.initialize(Image.java:799)
        at javafx.scene.image.Image.<init>(Image.java:702)
        at com.verisjudge.Main.<clinit>(Main.java:20)
        ... 3 more

How can I fix this?

**Comment by tbuzzelli** [comment]
The latest jar is pretty old. I'm working on getting a new release our. For now you can clone the repo and run it using Gradle. That will handle the proper linking of dependencies.

**Comment by CassieXx0215** [comment]
> The latest jar is pretty old. I'm working on getting a new release our. For now you can clone the repo and run it using Gradle. That will handle the proper linking of dependencies.

@tbuzzelli 
Hi, 
Could you give some more instructions on how to "run it using Gradle"? 
Sorry for not being familiar with Java project.
